### PR TITLE
QGIS Authentication Manager Integration

### PR DESCRIPTION
**Pull request by elpaso**
Proposed changes and what do they do:

* use the `QgsNetworkAccessManager` class for the network request
* QGIS native authentication configuration support
* QGIS native proxy configuration
* optional propagation of the authentication configuration from the CKAN server configuration to the result OGC endpoints

Note: the modifications done prior to the rebase have been thoroughfully tested in production for several months.

### CODE REVIEW

**Comment by BergWerkGIS** [comment]
@elpaso why did you close?
Your changes sound promising.
Just didn't have time yet to test.

**Comment by elpaso** [comment]
Sorry, just because I forgot that the the managers at Monsanto needed to give a final green light and an IP assessment. I will hopefully re-open it shortly.

**Comment by elpaso** [comment]
Good to go!

**Comment by BergWerkGIS** [comment]
@elpaso I merged your changes into a temporary branch (https://github.com/BergWerkGIS/QGIS-CKAN-Browser/tree/MonsantoCoQGISAuthenticationManager) as there are a few little things I'd like to rework.

Comments/suggestions welcome!

----

I'd like to keep that info:
https://github.com/BergWerkGIS/QGIS-CKAN-Browser/pull/14/files#diff-0db1154f063ad3740154b17a728075b3R320

The layout of the settings dialog seems a little screwed:

before:
image

now:
image

also:
image

**Comment by elpaso** [comment]
@BergWerkGIS I'll have a look to the settings dialog. What platform/QGIS version are you testing on?

This is how it looks on KDE (Kubuntu Trusty) and QGIS 2.18 (4K display):
ckan

**Comment by BergWerkGIS** [comment]
> I'll have a look to the settings dialog. What platform/QGIS version are you testing on?

@elpaso I've updated my above post with system information.

On Linux it seems that the hidden authentication widgets are causing the widgets on the left to be shrunk too much.

On Windows this happens when I shrink the dialog to its minimum size.

I've created a new PR #15, let's continue discussion there.

**Pull request merged**
