### PR TITLE
QGIS Authentication Manager Integration - take 2

### PR DESCRIPTION
**Pull request by BergWerkGIS**
Sort out details of PR `QGIS Authentication Manager Integration`: #14

### CODE REVIEW

**Comment by elpaso** [comment]
@BergWerkGIS hi, is there anything I help with?

**Comment by BergWerkGIS** [comment]
@elpaso thanks for the offer.
Any help with the mangled GUI elements (https://github.com/BergWerkGIS/QGIS-CKAN-Browser/pull/14#issuecomment-289208080) is very much appreciated as I don't have any free time available at the moment.


eg (**QGIS 2.18.4, Win10**):
image

**Comment by elpaso** [comment]
@BergWerkGIS unfortunately I cannot reproduce it, this snapshot is with qgis 2.14 on a win10 64bit VM (I don't think that 2.18 would be different: that's a pure QT thing):
ckan_win10

BTW, I will fire qt designer and see if I can rework the layout.

**Comment by BergWerkGIS** [comment]
@elpaso If I remember correctly it happened when I shrunk the dialog a bit.

**Comment by elpaso** [comment]
@BergWerkGIS I tried to shrink to the minimum allowed width but I still cannot reproduce the issue.

**Comment by BergWerkGIS** [comment]
done in #20

**Pull request closed without merging**
